### ISSUE TITLE
Not all libc versions have the single precision transcendental functions

### ISSUE THREAD

**Issue by sgjesse** [dartino/sdk#552]
The LK build fails after https://github.com/dartino/sdk/commit/7d94a4d5d58523cc4da10833e7c338bdd0c3d997.

```
out/build-qemu-virt-dartino/out/...mod.o: In function `Native_DoubleAtan':
/mnt/data/b/build/slave/dartino-lk-debug-arm-qemu/build/sdk/out/../src/vm/natives.cc:870: undefined reference to `atanf'
out/build-qemu-virt-dartino/out/...mod.o: In function `Native_DoubleExp':
/mnt/data/b/build/slave/dartino-lk-debug-arm-qemu/build/sdk/out/../src/vm/natives.cc:872: undefined reference to `expf'
out/build-qemu-virt-dartino/out/...mod.o: In function `Native_DoubleLog':
/mnt/data/b/build/slave/dartino-lk-debug-arm-qemu/build/sdk/out/../src/vm/natives.cc:873: undefined reference to `logf'
out/build-qemu-virt-dartino/out/...mod.o: In function `Native_DoubleAtan2':
/mnt/data/b/build/slave/dartino-lk-debug-arm-qemu/build/sdk/out/../src/vm/natives.cc:882: undefined reference to `atan2f'
```

**Comment by travisg** [comment]
Pretty easy to add new ones, the math routines in LK are largely added as needed, usually cribbed from FreeBSD or bionic.
